apiVersion: apps/v1
kind: Deployment
metadata:
  name: bili-backend
  labels:
    app: bili-backend
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bili-backend
  template:
    metadata:
      labels:
        app: bili-backend
    spec:
      initContainers:
        - name: prisma-migrate
          image: flower0wine/bili:latest
          command: ["pnpm", "--dir", "packages/backend", "exec", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: managed-secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      containers:
        - name: bili-backend
          image: flower0wine/bili:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: managed-secret
          ports:
            - containerPort: 9000
